name: Frontend
on:
  push:
    branches:
      - master

jobs:
  Tests:
    name: Tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -f ./client/Dockerfile.dev ./client -t arch23/multi-docker-example
      - run: docker run -e CI=true arch23/multi-docker-example npm run test      

  Build-client:
    name: Build-client
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: ./client
          file: ./client/Dockerfile
          tags: arch23/multi-docker-client
          outputs: type=docker,dest=/tmp/multi-docker-client.tar
      - uses: actions/upload-artifact@v3
        with:
          name: multi-docker-client
          path: /tmp/multi-docker-client.tar

  Build-nginx:
    name: Build-nginx
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          tags: arch23/multi-docker-nginx
          outputs: type=docker,dest=/tmp/multi-docker-nginx.tar
      - uses: actions/upload-artifact@v3
        with:
          name: multi-docker-nginx
          path: /tmp/multi-docker-nginx.tar

  Build-server:
    name: Build-server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: ./server
          file: ./server/Dockerfile
          tags: arch23/multi-docker-server
          outputs: type=docker,dest=/tmp/multi-docker-server.tar
      - uses: actions/upload-artifact@v3
        with:
          name: multi-docker-server
          path: /tmp/multi-docker-server.tar

  Build-worker:
    name: Build-worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: ./worker/Dockerfile
          tags: arch23/multi-docker-worker
          outputs: type=docker,dest=/tmp/multi-docker-worker.tar
      - uses: actions/upload-artifact@v3
        with:
          name: multi-docker-worker
          path: /tmp/multi-docker-worker.tar

  DockerHub-upload:
    name: Docker-login
    needs: [Build-client, Build-nginx, Build-server, Build-worker]
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin
      - uses: actions/download-artifact@v3
        with:
          path: /tmp
      - run: docker load -i /tmp/multi-docker-client/multi-docker-client.tar
      - run: docker load -i /tmp/multi-docker-nginx/multi-docker-nginx.tar
      - run: docker load -i /tmp/multi-docker-server/multi-docker-server.tar
      - run: docker load -i /tmp/multi-docker-worker/multi-docker-worker.tar
      - run: docker push arch23/multi-docker-client
      - run: docker push arch23/multi-docker-nginx
      - run: docker push arch23/multi-docker-server
      - run: docker push arch23/multi-docker-worker

