name: Frontend
on:
  push:
    branches:
      - master

jobs:
  Tests:
    name: Tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -f ./client/Dockerfile.dev ./client -t arch23/multi-docker-example
      - run: docker run -e CI=true arch23/multi-docker-example npm run test      

  Build-client:
    name: Build-client
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build ./client -t arch23/multi-docker-client -o type=docker,dest=/tmp/multi-docker-client.tar
  
  # Build-nginx:
  #   name: Build-nginx
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: docker build ./nginx -t arch23/multi-docker-nginx

  # Build-server:
  #   name: Build-server
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: docker build ./server -t arch23/multi-docker-server

  # Build-worker:
  #   name: Build-worker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: docker build ./worker -t arch23/multi-docker-worker

  # DockerHub-upload:
  #   name: Docker-login
  #   needs: [Build-client, Build-nginx, Build-server, Build-worker]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

